### ISSUE TITLE
Tests are missing

### ISSUE THREAD

**Issue by geeqla** [johnayeni/filter-app-vue-js#2]
A folder with tests is not available.

`npm test` command produces:

> Error: Can't find a root directory while resolving a config file path.
> Provided path to resolve: test/unit/jest.conf.js

**Comment by johnayeni** [comment]
Sorry for this age-long late reply. I have fixed this by removed the test command and replacing the test script with an output that just says "no tests specified". This tutorial wasn't meant to consider tests for the application. Thank you very much @geeqla
